/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RequestAQuoteRouteImport } from './routes/request-a-quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as FreeConsultationRouteImport } from './routes/free-consultation'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesVideoEditingRouteImport } from './routes/services.video-editing'
import { Route as ServicesSocialMediaManagementRouteImport } from './routes/services.social-media-management'
import { Route as ServicesInfluencerManagementRouteImport } from './routes/services.influencer-management'
import { Route as ServicesDigitalMarketingRouteImport } from './routes/services.digital-marketing'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAQuoteRoute = RequestAQuoteRouteImport.update({
  id: '/request-a-quote',
  path: '/request-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeConsultationRoute = FreeConsultationRouteImport.update({
  id: '/free-consultation',
  path: '/free-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVideoEditingRoute = ServicesVideoEditingRouteImport.update({
  id: '/video-editing',
  path: '/video-editing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSocialMediaManagementRoute =
  ServicesSocialMediaManagementRouteImport.update({
    id: '/social-media-management',
    path: '/social-media-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInfluencerManagementRoute =
  ServicesInfluencerManagementRouteImport.update({
    id: '/influencer-management',
    path: '/influencer-management',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDigitalMarketingRoute =
  ServicesDigitalMarketingRouteImport.update({
    id: '/digital-marketing',
    path: '/digital-marketing',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/free-consultation': typeof FreeConsultationRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/influencer-management': typeof ServicesInfluencerManagementRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/free-consultation': typeof FreeConsultationRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/influencer-management': typeof ServicesInfluencerManagementRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/faqs': typeof FaqsRoute
  '/free-consultation': typeof FreeConsultationRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/request-a-quote': typeof RequestAQuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/services/digital-marketing': typeof ServicesDigitalMarketingRoute
  '/services/influencer-management': typeof ServicesInfluencerManagementRoute
  '/services/social-media-management': typeof ServicesSocialMediaManagementRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/faqs'
    | '/free-consultation'
    | '/portfolio'
    | '/privacy-policy'
    | '/request-a-quote'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/services/digital-marketing'
    | '/services/influencer-management'
    | '/services/social-media-management'
    | '/services/video-editing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/faqs'
    | '/free-consultation'
    | '/portfolio'
    | '/privacy-policy'
    | '/request-a-quote'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/services/digital-marketing'
    | '/services/influencer-management'
    | '/services/social-media-management'
    | '/services/video-editing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/cookie-policy'
    | '/faqs'
    | '/free-consultation'
    | '/portfolio'
    | '/privacy-policy'
    | '/request-a-quote'
    | '/services'
    | '/terms'
    | '/testimonials'
    | '/services/digital-marketing'
    | '/services/influencer-management'
    | '/services/social-media-management'
    | '/services/video-editing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FaqsRoute: typeof FaqsRoute
  FreeConsultationRoute: typeof FreeConsultationRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RequestAQuoteRoute: typeof RequestAQuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-quote': {
      id: '/request-a-quote'
      path: '/request-a-quote'
      fullPath: '/request-a-quote'
      preLoaderRoute: typeof RequestAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-consultation': {
      id: '/free-consultation'
      path: '/free-consultation'
      fullPath: '/free-consultation'
      preLoaderRoute: typeof FreeConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/video-editing': {
      id: '/services/video-editing'
      path: '/video-editing'
      fullPath: '/services/video-editing'
      preLoaderRoute: typeof ServicesVideoEditingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media-management': {
      id: '/services/social-media-management'
      path: '/social-media-management'
      fullPath: '/services/social-media-management'
      preLoaderRoute: typeof ServicesSocialMediaManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/influencer-management': {
      id: '/services/influencer-management'
      path: '/influencer-management'
      fullPath: '/services/influencer-management'
      preLoaderRoute: typeof ServicesInfluencerManagementRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/digital-marketing': {
      id: '/services/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/services/digital-marketing'
      preLoaderRoute: typeof ServicesDigitalMarketingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesDigitalMarketingRoute: typeof ServicesDigitalMarketingRoute
  ServicesInfluencerManagementRoute: typeof ServicesInfluencerManagementRoute
  ServicesSocialMediaManagementRoute: typeof ServicesSocialMediaManagementRoute
  ServicesVideoEditingRoute: typeof ServicesVideoEditingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDigitalMarketingRoute: ServicesDigitalMarketingRoute,
  ServicesInfluencerManagementRoute: ServicesInfluencerManagementRoute,
  ServicesSocialMediaManagementRoute: ServicesSocialMediaManagementRoute,
  ServicesVideoEditingRoute: ServicesVideoEditingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FaqsRoute: FaqsRoute,
  FreeConsultationRoute: FreeConsultationRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RequestAQuoteRoute: RequestAQuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
